name: Build Jekyll and Deploy to gh-pages
on:
  push:
    branches: [ source ]
permissions:
  contents: write
concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: '2.6.9'
          bundler-cache: true

      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build --trace

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
